"""add_error_message_to_runs

Revision ID: 98fde155bafe
Revises: c5f2a1b3d4e6
Create Date: 2026-06-21 12:01:52.150652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fde155bafe'
down_revision: Union[str, Sequence[str], None] = 'c5f2a1b3d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'error_message')
    # ### end Alembic commands ###
